# Configuration file for the Sphinx documentation builder.
# https://www.sphinx-doc.org/en/master/usage/configuration.html
# Generated by: ./iclaude.sh --init-docs

# -- Project information -------------------------------------------------------
project = "snxui"
author = "snxui contributors"

# Source root is docs/ (not docs/sphinx/), so toctree paths are relative to docs/.
# sphinx-build is called with: sphinx-build -b html -c docs/sphinx docs docs/sphinx/_build/html
root_doc = "sphinx/index"

# -- General configuration -----------------------------------------------------
extensions = [
    "myst_parser",
    "sphinx_design",
    "sphinx_copybutton",
    "sphinxcontrib.mermaid",
]

# sphinx-llms-txt: generates llms.txt and llms-full.txt for AI agents
# Install: pip install sphinx-llms-txt
try:
    import sphinx_llms_txt  # noqa: F401
    extensions.append("sphinx_llms_txt")
except ImportError:
    pass  # Optional — docs build without it

# MyST Parser — use Markdown with full Sphinx capabilities
myst_enable_extensions = [
    "colon_fence",   # ::: blocks as alternative to ``` for directives
    "deflist",       # Definition lists
    "fieldlist",     # Field lists
    "attrs_inline",  # Inline attributes {.class}
]

# File formats
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# Exclude patterns (relative to docs/sphinx/)
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
]

# -- HTML output ---------------------------------------------------------------
html_theme = "furo"
html_title = "snxui Documentation"

# Furo theme options
html_theme_options = {
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
}

# -- sphinx-llms-txt -----------------------------------------------------------
# AI-first documentation: generates llms.txt and llms-full.txt
# These files allow AI agents to consume documentation efficiently
# See: https://llmstxt.org/

# For Python API docs, add 'sphinx-autoapi' to extensions and install it:\n# pip install sphinx-autoapi
